---
# handlers file for snort

- name: snort service is restarted
  service:
    name: "{{ service_name }}"
    state: restarted
    sleep: 5
  become: true

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded
  become: true
